---
- name: Deploy alert_smtp
  hosts: nodes
  become: yes
  gather_facts: no

  tasks:
  - name: Copy the alert_smtp script to the nodes
    copy:
      src: ../agents/alert_smtp_filtered.sh
      mode: 0750
      owner: hacluster
      group: haclient
      dest: /var/lib/pacemaker/alert_smtp.sh   
     

  - name: remove the debug alert_smtp script
    file:
      dest: /var/lib/pacemaker/alert_smtp_actual.sh
      state: absent
